/**
 * 검색용 한글↔영문 동의어. DB에 있는 텍스트를 한글/영문/동의어로 찾을 수 있게 함.
 * 키: 한글 또는 대표 표기, 값: [영문·동의어 목록]. 소문자로 매칭됨.
 */
export const SEARCH_SYNONYMS: Record<string, string[]> = {
  // ─── 카메라 브랜드 ───
  일포드: ["ilford"],
  캐논: ["canon"],
  코닥: ["kodak"],
  펜탁스: ["pentax"],
  니콘: ["nikon"],
  올림푸스: ["olympus"],
  라이카: ["leica"],
  하셀블라드: ["hasselblad"],
  미놀타: ["minolta"],
  소니: ["sony"],
  후지: ["fuji", "fujifilm"],
  아그파: ["agfa"],
  포드: ["ford"],
  콘탁스: ["contax"],
  브론يكا: ["bronica"],
  마미야: ["mamiya"],
  horseman: ["호스맨"],
  호스맨: ["horseman"],
  linhof: ["린호프"],
  린호프: ["linhof"],
  cambo: ["캄보"],
  캄보: ["cambo"],
  arca: ["아르카"],
  아르카: ["arca"],
  sinar: ["시나"],
  시나: ["sinar"],
  toyo: ["토요"],
  토요: ["toyo"],
  wista: ["비스타"],
  비스타: ["wista"],
  chamonix: ["샤모니"],
  샤모니: ["chamonix"],
  intrepid: ["인트레피드"],
  인트레피드: ["intrepid"],
  graflex: ["그래플렉스"],
  그래플렉스: ["graflex"],
  speed: ["스피드"],
  graphic: ["그래픽"],
  crown: ["크라운"],
  super: ["슈퍼"],

  // ─── 필름 브랜드·제품명 ───
  골드: ["gold"],
  gold: ["골드"],
  포트라: ["portra"],
  portra: ["포트라"],
  울트라: ["ultra"],
  ultra: ["울트라"],
  트리엑스: ["tri-x", "tri x"],
  "tri-x": ["트리엑스"],
  "tri x": ["트리엑스"],
  tmax: ["티맥스"],
  티맥스: ["tmax"],
  더블엑스: ["double x", "doublex"],
  "double x": ["더블엑스"],
  doublex: ["더블엑스"],
  hp5: ["hp5", "에이치피5"],
  에이치피5: ["hp5"],
  델타: ["delta"],
  delta: ["델타"],
  파나: ["pan f", "panf"],
  "pan f": ["파나"],
  panf: ["파나"],
  fp4: ["fp4", "에프피4"],
  에프피4: ["fp4"],
  xp2: ["xp2"],
  프로: ["pro"],
  프로400: ["pro 400h", "pro400h"],
  "pro 400h": ["프로400"],
  pro400h: ["프로400"],
  아크로스: ["acros"],
  acros: ["아크로스"],
  네오팬: ["neopan"],
  neopan: ["네오팬"],
  베리오: ["verio"],
  verio: ["베리오"],
  실비아: ["silvia"],
  silvia: ["실비아"],
  실버: ["silver"],
  silver: ["실버"],
  c41: ["c41", "씨41"],
  "씨41": ["c41"],
  흑백: ["bw", "b&w", "black white", "black and white"],
  bw: ["흑백"],
  "b&w": ["흑백"],
  컬러: ["color", "colour"],
  color: ["컬러"],
  colour: ["컬러"],
  네거티브: ["negative"],
  negative: ["네거티브"],
  슬라이드: ["slide"],
  slide: ["슬라이드"],
  역광: ["reversal"],
  reversal: ["역광"],

  // ─── 인화지·용지 브랜드·타입 ───
  러스티: ["lustre"],
  lustre: ["러스티"],
  러스트: ["lustre"],
  글로스: ["gloss", "glossy"],
  gloss: ["글로스"],
  glossy: ["글로스"],
  매트: ["matte", "matt", "mat"],
  matte: ["매트"],
  matt: ["매트"],
  mat: ["매트"],
  펄: ["pearl"],
  pearl: ["펄"],
  새틴: ["satin"],
  satin: ["새틴"],
  광택: ["glossy", "gloss"],
  무광: ["matte", "matt"],
  광택지: ["glossy paper"],
  무광지: ["matte paper"],
  염화은: ["chlorobromide", "chloride"],
  chlorobromide: ["염화은"],
  bromide: ["브로마이드"],
  브로마이드: ["bromide"],
  광학: ["optical"],
  optical: ["광학"],
  RC: ["rc", "레진코팅"],
  FB: ["fb", "파이버", "fiber"],
  파이버: ["fiber", "fb"],
  fiber: ["파이버", "fb"],
  레진코팅: ["rc", "resin coated"],
  "resin coated": ["레진코팅", "rc"],
  바리언트: ["variants"],
  variants: ["바리언트"],
  멀티그레이드: ["multigrade"],
  multigrade: ["멀티그레이드"],
  mg: ["mg", "멀티그레이드"],
  멀티그레이드: ["multigrade", "mg"],
  웜톤: ["warmtone", "warm tone"],
  warmtone: ["웜톤"],
  "warm tone": ["웜톤"],
  쿨톤: ["cooltone", "cool tone"],
  cooltone: ["쿨톤"],
  "cool tone": ["쿨톤"],
  클래식: ["classic"],
  classic: ["클래식"],
  프리즈매: ["prism"],
  prism: ["프리즈매"],
  아티잔: ["artisan"],
  artisan: ["아티잔"],
  갤러리: ["gallery"],
  gallery: ["갤러리"],
  kentmere: ["켄트메어"],
  켄트메어: ["kentmere"],
  foma: ["포마"],
  포마: ["foma"],
  adox: ["아독스"],
  아독스: ["adox"],
  bergger: ["베르거"],
  베르거: ["berger"],
  oriental: ["오리엔탈"],
  오리엔탈: ["oriental"],

  // ─── 판형·포맷 ───
  판형: ["format"],
  포맷: ["format"],
  format: ["포맷", "판형"],
  대형: ["large", "format", "4x5", "8x10", "large format"],
  중형: ["medium", "120", "120mm", "6x6", "6x7", "medium format"],
  소형: ["35mm", "35밀리", "135", "small"],
  "35밀리": ["35mm", "135", "소형"],
  "35mm": ["35밀리", "135", "소형"],
  "120": ["120", "120mm", "6x6", "6x7", "중형"],
  "120mm": ["120", "중형"],
  "135": ["135", "35mm", "소형"],
  "4x5": ["4x5", "4*5", "large"],
  "4*5": ["4x5", "4x5"],
  "8x10": ["8x10", "8*10", "large"],
  "8*10": ["8x10", "8x10"],
  "5x7": ["5x7", "5*7"],
  "5*7": ["5x7"],
  "6x6": ["6x6", "6*6"],
  "6*6": ["6x6"],
  "6x7": ["6x7", "6*7"],
  "6*7": ["6x7"],
  "6x9": ["6x9", "6*9"],
  "6*9": ["6x9"],
  "6x4.5": ["645", "6x4.5"],
  "645": ["6x4.5", "6x45"],
  "6x45": ["645"],
  "4x6": ["4x6"],
  "10x12": ["10x12"],
  "11x14": ["11x14"],
  "16x20": ["16x20"],
  "full frame": ["풀프레임", "35mm"],
  풀프레임: ["full frame", "35mm"],
  하프: ["half", "half frame"],
  "half frame": ["하프"],
  "large format": ["대형", "라지포맷"],
  라지포맷: ["large format", "대형"],
  "medium format": ["중형", "미디엄포맷"],
  미디엄포맷: ["medium format", "중형"],

  // ─── 렌즈·조리개·초점거리 ───
  렌즈: ["lens"],
  lens: ["렌즈"],
  표준: ["normal", "standard"],
  normal: ["표준"],
  광각: ["wide", "wide angle"],
  wide: ["광각"],
  망원: ["telephoto", "tele"],
  telephoto: ["망원"],
  tele: ["망원"],
  줌: ["zoom"],
  zoom: ["줌"],
  단초점: ["prime", "fixed"],
  prime: ["단초점"],
  fixed: ["단초점"],
  "50mm": ["50밀리", "오십"],
  "50밀리": ["50mm"],
  "35mm lens": ["35mm", "광각"],
  "80mm": ["80밀리"],
  "90mm": ["90밀리"],
  "150mm": ["150밀리"],
  "210mm": ["210밀리"],
  "300mm": ["300밀리"],
  조리개: ["aperture", "f-stop"],
  aperture: ["조리개"],
  "f-stop": ["조리개"],
  f2: ["f2", "에프2"],
  "f2.8": ["f2.8"],
  f4: ["f4"],
  "f5.6": ["f5.6"],
  f8: ["f8"],
  f11: ["f11"],
  f16: ["f16"],
  f22: ["f22"],
  f32: ["f32"],
  개방: ["open", "wide open"],
  개방조리개: ["open aperture"],
  심도: ["dof", "depth of field"],
  "depth of field": ["심도"],
  dof: ["심도"],

  // ─── 인화·현상 관련 ───
  인화: ["print", "printing"],
  print: ["인화"],
  printing: ["인화"],
  인화지: ["paper", "printing paper"],
  페이퍼: ["paper"],
  paper: ["인화지", "페이퍼"],
  현상: ["development", "developing"],
  development: ["현상"],
  developing: ["현상"],
  현상액: ["developer"],
  developer: ["현상액"],
  정착: ["fixer", "fixing"],
  fixer: ["정착액", "정착"],
  fixing: ["정착"],
  정착액: ["fixer"],
  중지: ["stop"],
  stop: ["중지"],
  수세: ["wash", "washing"],
  wash: ["수세"],
  washing: ["수세"],
  노출: ["exposure"],
  exposure: ["노출"],
  노출시간: ["exposure time"],
  "exposure time": ["노출시간"],
  감도: ["iso", "asa", "speed"],
  iso: ["감도"],
  asa: ["감도"],
  speed: ["감도"],
  콘트라스트: ["contrast"],
  contrast: ["콘트라스트"],
  농도: ["density"],
  density: ["농도"],
  그레이: ["gray", "grey"],
  gray: ["그레이"],
  grey: ["그레이"],
  그레이스케일: ["grayscale", "greyscale"],
  grayscale: ["그레이스케일"],
  greyscale: ["그레이스케일"],
  흑백인화: ["bw print", "black and white print"],
  "bw print": ["흑백인화"],
  컬러인화: ["color print"],
  "color print": ["컬러인화"],
  디지털인화: ["digital print"],
  "digital print": ["디지털인화"],
  광학인화: ["optical print"],
  "optical print": ["광학인화"],
  엔라이징: ["enlarging"],
  enlarging: ["엔라이징"],
  확대: ["enlarge", "enlargement"],
  enlarge: ["확대"],
  enlargement: ["확대"],
  감광: ["sensitized"],
  감광지: ["sensitized paper"],
  RC지: ["rc paper", "rc"],
  "rc paper": ["RC지"],
  FB지: ["fb paper", "fiber paper"],
  "fb paper": ["FB지"],
  "fiber paper": ["FB지", "파이버지"],
  파이버지: ["fiber paper", "fb"],

  // ─── 기타 공통 ───
  카메라: ["camera"],
  camera: ["카메라"],
  브랜드: ["brand"],
  brand: ["브랜드"],
  사이즈: ["size"],
  size: ["사이즈"],
  타입: ["type"],
  type: ["타입"],
  종류: ["kind", "type"],
  kind: ["종류"],
  이름: ["name"],
  name: ["이름"],
  설명: ["description"],
  description: ["설명"],
  필름: ["film"],
  film: ["필름"],
  프레임: ["frame"],
  frame: ["프레임"],
  시트: ["sheet"],
  sheet: ["시트"],
  롤: ["roll"],
  roll: ["롤"],
  박스: ["box"],
  box: ["박스"],
  장: ["sheets"],
  sheets: ["장"],
  매: ["sheets"],
  팩: ["pack"],
  pack: ["팩"],
  올: ["roll"],
  실버젤라틴: ["silver gelatin"],
  "silver gelatin": ["실버젤라틴"],
  젤라틴: ["gelatin"],
  gelatin: ["젤라틴"],
  유제: ["emulsion"],
  emulsion: ["유제"],
  코팅: ["coating"],
  coating: ["코팅"],
  두께: ["thickness"],
  thickness: ["두께"],
  중량: ["weight"],
  weight: ["중량"],
  gsm: ["gsm", "그램"],
  그램: ["gsm"],
};
